version: '3.6'

services:
  balancer:
    build: ./nginx
    env_file:
      - .env
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./code:/code
      - ./sock:/sock
      - ./nginx/pass/admin.txt:/etc/nginx/passwords/admin.txt
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    logging:
      options:
        max-size: 1000m
    restart: 'no'
    networks:
      code-network:
        ipv4_address: 10.5.0.3

  php:
    build: ./php
    volumes:
      - ./code:/code
      - ./sock:/sock
      - ./php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    networks:
      code-network:
        ipv4_address: 10.5.0.4

  mysql:
    image: mariadb
    ports: 
      - '3306:3306'
    env_file:
      - .env
    restart: 'no' 
    volumes:
      - ./mysql/scripts:/docker-entrypoint-initdb.d
      - ./mysql/db:/var/lib/mysql
    networks:
      code-network:
        ipv4_address: 10.5.0.5  


networks:
  code-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
