version: '3.6'

services:
  balancer:
    build: ./nginx
    env_file:
      - .env
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./app:/app
      - ./sock:/sock
      - ./nginx/pass/admin.txt:/etc/nginx/passwords/admin.txt
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    logging:
      options:
        max-size: 1000m
    restart: 'no'
    networks:
      code-network:
        ipv4_address: 10.5.0.3

  php:
    build: ./php
    volumes:
      - ./app:/app
      - ./sock:/sock
      - ./php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    ports: 
      - '8000:80'
      - '8443:443'  
    links: 
      - mysql:db
    networks:
      code-network:
        ipv4_address: 10.5.0.4

  mysql:
    image: mariadb:latest
    ports: 
      - '3306:3306'
    env_file:
      - .env
    restart: 'no' 
    volumes:
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/custom.cnf
      - ./mysql/scripts:/docker-entrypoint-initdb.d
      - ./mysql/db:/var/lib/mysql
    networks:
      code-network:
        ipv4_address: 10.5.0.5  

  # app:
  #   build: ./app
  #   ports: 
  #     - '8000:80'
  #     - '8443:443'
  #     - '10022:22'
  #   env_file:
  #     - .env
  #   volumes:
  #   #  - ./sock:/sock
  #     - ./app/:/app/
  #   restart: 'no' 
  #   links: 
  #     - mysql:db
  #   networks:
  #     code-network:
  #       ipv4_address: 10.5.0.6 
   

networks:
  code-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
